title = "Measurements of horizontal, vertical angles and lengths of the sides of tacheometric traverse"

["D"]
    D100 = -0.2
    D150 = -0.2
    D200 = -0.3

["dir_angles"]
    initial_angle = "218°51.4'"
    final_angle = "240°32.1'"

["coords"]
    initial_x = 2168.6
    initial_y = 1592.1
    final_x = 1850.5
    final_y = 1706.5

["heights"]
    initial_h = 636.84
    final_h = 640.52

["ПП26"]
    i = 1.30

    ["ПП26"."hor_angle"]
    l_prev_angle = "0°01.5'"
    l_next_angle = "168°14.5'"
    r_prev_angle = "181°31.0'"
    r_next_angle = "349°44.5'"

    ["ПП26"."vert_angle"]
    prev_V = ""
    l_prev_angle = ""
    r_prev_angle = ""
    next_V= 1
    l_next_angle = "1°23.0'"
    r_next_angle = "-1°24.0'"


    ["ПП26"."l"]
    l_prev_length = ""
    r_prev_length = ""
    l_next_length = "101.5"
    r_next_length = "101.5"

    ["ПП26"."data"]
        i = 1.37
        H = 636.84
        L = "-3°06.0'"
        R = "3°06.0'"
        M0 = "0°0'"

        ["ПП26"."data"."1"]
        hor_angle = "180°56'"
        vert_angle = "-0°59'"
        V = 1.37
        D = 145.8

        ["ПП26"."data"."2"]
        hor_angle = "148°57'"
        vert_angle = "-0°36'"
        V = 2
        D = 50.2

        ["ПП26"."data"."3"]
        hor_angle = "198°14'"
        vert_angle = "-0°09.5'"
        V = 2
        D = 141.6

        ["ПП26"."data"."4"]
        hor_angle = "216°05'"
        vert_angle = "0°50.5'"
        V = 2.5
        D = 58.4

        ["ПП26"."data"."5"]
        hor_angle = "211°52'"
        vert_angle = "-0°09'"
        V = 2
        D = 196.2

        ["ПП26"."data"."6"]
        hor_angle = "230°20'"
        vert_angle = "+1°20.5'"
        V = 1.37
        D = 200.1

        ["ПП26"."data"."7"]
        hor_angle = "40°01'"
        vert_angle = "+1°24.5'"
        V = 2.50
        D = 35

        ["ПП26"."data"."8"]
        hor_angle = "91°58'"
        vert_angle = "0°31'"
        V = 2
        D = 107

        ["ПП26"."data"."9"]
        hor_angle = "54°12'"
        vert_angle = "-0°2.5'"
        V = 1.37
        D = 83.8

        ["ПП26"."data"."10"]
        hor_angle = "233°32'"
        vert_angle = "+2°9.5'"
        V = 2.5
        D = 159

        ["ПП26"."data"."11"]
        hor_angle = "262°31'"
        vert_angle = "+2°48.5'"
        V = 2
        D = 120.2

[I]
    i = 1.45

    [I."hor_angle"]
    l_prev_angle = "0°02.0'"
    l_next_angle = "130°24.0'"
    r_prev_angle = "182°22.5'"
    r_next_angle = "312°43.5'"

    [I."vert_angle"]
    prev_V = 2
    l_prev_angle = "-1°14.0'"
    r_prev_angle = "1°15.0'"
    next_V= 2
    l_next_angle = "2°17.0'"
    r_next_angle = "-2°18.0'"

    [I."l"]
    l_prev_length = "101.5"
    r_prev_length = "101.2"
    l_next_length = "110.3"
    r_next_length = "110.1"

[II]
    i = 1.36

    [II."hor_angle"]
    l_prev_angle = "0°03.0'"
    l_next_angle = "98°02.0'"
    r_prev_angle = "181°23.5'"
    r_next_angle = "279°22.0'"

    [II."vert_angle"]
    prev_V = 2
    l_prev_angle = "-1°40.0'"
    r_prev_angle = "1°39.0'"
    next_V= 2
    l_next_angle = "1°19.5'"
    r_next_angle = "-1°20.5'"

    [II."l"]
    l_prev_length = "110.2"
    r_prev_length = "110.0"
    l_next_length = "197.0"
    r_next_length = "196.4"

[III]
    i = 1.52

    [III."hor_angle"]
    l_prev_angle = "0°02.5'"
    l_next_angle = "306°39.5'"
    r_prev_angle = "182°23.0'"
    r_next_angle = "128°59.0'"

    [III."vert_angle"]
    prev_V = 1.5
    l_prev_angle = "-1°08.5'"
    r_prev_angle = "1°09.0'"
    next_V= 2
    l_next_angle = "-1°56.0'"
    r_next_angle = "1°57.0'"

    [III."l"]
    l_prev_length = "196.6"
    r_prev_length = "196.6"
    l_next_length = "189.7"
    r_next_length = "189.3"

["ПП68"]
    i = 1.46

    ["ПП68"."hor_angle"]
    l_prev_angle = "0°03.5'"
    l_next_angle = "218°36.0'"
    r_prev_angle = "182°24.0'"
    r_next_angle = "40°55.5'"

    ["ПП68"."vert_angle"]
    prev_V = 1.5
    l_prev_angle = "2°07.5'"
    r_prev_angle = "-2°06.5'"
    next_V= ""
    l_next_angle = ""
    r_next_angle = ""

    ["ПП68"."l"]
    l_prev_length = "189.5"
    r_prev_length = "188.9"
    l_next_length = ""
    r_next_length = ""
